name: Infrastructure cost analyzer

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.tfvars.json"
  workflow_dispatch:

env:
  IAC_AWS: iac/terraform/aws

jobs:
  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Create Terraform plan
      - name: "Install terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: "Terraform init"
        id: init
        run: terraform init
        working-directory: ${{ env.IAC_AWS }}

      - name: "Terraform plan"
        id: plan
        run: terraform plan -out plan.tfplan
        working-directory: ${{ env.IAC_AWS }}

      - name: "Terraform show"
        id: show
        run: terraform show -json plan.tfplan | tee plan.json
        working-directory: ${{ env.IAC_AWS }}

      # - name: "Save Plan JSON"
      #   run: echo '${{ steps.show.outputs.stdout }}' > plan.json # Do not change

      # Run Infracost
      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        run: infracost breakdown --path plan.json --format json --usage-file infracost-usage.yml --out-file /tmp/infracost.json
        working-directory: ${{ env.IAC_AWS }}

      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          behavior: update

      # Run Open Policy Agent
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v1

      - name: Run OPA
        run: opa eval --input /tmp/infracost.json -d iac/policies/cost-policy.rego --format pretty "data.infracost.deny" | tee /tmp/opa.out

      - name: Check Policies
        run: |
          denyReasons=$(</tmp/opa.out)
          if [ "$denyReasons" != "[]" ]; then
            echo -e "::error::Cost policy check failed, please check with @donhector before proceeding with the change:\n$denyReasons"
            exit 1
          else
            echo "::info::Cost policy check passed."
          fi
